benchmarks:
- freetype2-2017
- bloaty_fuzz_target
concurrent_builds: null
description: null
docker_registry: gcr.io/fuzzbench
experiment: docker-test
experiment_filestore: /home/wolffd/scratch/experiment-data
fuzzers:
- afl
- libfuzzer
git_hash: 8858be7e05035103eac5db46ae682fad2c84fe5e
local_experiment: true
max_total_time: 910
no_dictionaries: false
no_seeds: true
oss_fuzz_corpus: false
report_filestore: /home/wolffd/scratch/report-data
runner_machine_type: n1-standard-1
runner_memory: 12GB
runner_num_cpu_cores: 1
seeds_per_trial_dir: /home/wolffd/git/fuzzbench-seed-sampling/seeds
trials: 2
use_seeds_per_trial: true
